### ISSUE TITLE
iconv fails to build in a production environment

### ISSUE THREAD

**Issue by JohnAdamsy** [stldo/url-slug#1]
What could be the cause of this?  It works fine in my local environment.

```
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/www/my-app/node_modules/url-slug/node_modules/iconv/lib/iconv.js:29:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by stldo** [comment]
@JohnAdamsy, did you solved this?

**Comment by JohnAdamsy** [comment]
@sbtoledo  I came to learn that it does that when the env is set "production". Still don't know why though?

**Comment by stldo** [comment]
@JohnAdamsy besides your issue, node-iconv was having some transliteration problems on CentOS machines, so it was changed for node-unidecode. I think that it should work now, node-unidecode doesn't compile anything.
